# Generated by Django 3.1.1 on 2020-10-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uspsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uspsa_num', models.CharField(max_length=10, unique=True)),
                ('division', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'USPSA',
                'verbose_name_plural': 'USPSA',
                'db_table': 'uspsa',
                'unique_together': {('uspsa_num', 'division')},
            },
        ),
    ]
