# Generated by Django 3.1.1 on 2020-10-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_factor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uspsa',
            name='uspsa_num',
            field=models.CharField(max_length=10),
        ),
    ]
