# Generated by Django 4.1.4 on 2022-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_factor', '0002_auto_20201002_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uspsa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
