# Generated by Django 3.1.1 on 2021-06-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gridiron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_mem1', models.CharField(max_length=20, unique=True)),
                ('team_mem2', models.CharField(max_length=20, unique=True)),
                ('team_mem3', models.CharField(max_length=20, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GRIDIRON',
                'verbose_name_plural': 'GRIDIRON',
                'db_table': 'gridiron',
            },
        ),
    ]
