# Generated by Django 4.1.4 on 2022-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_iron', '0002_gridiron_team_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridiron',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
